steps:
  # Step 1: Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/gen-lang-client-0318381471/cloud-run-source-deploy/lionovart-web:$COMMIT_SHA', '.']

  # Step 2: Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/gen-lang-client-0318381471/cloud-run-source-deploy/lionovart-web:$COMMIT_SHA']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'lionovart-next-tailwind'
    - '--image'
    - 'us-central1-docker.pkg.dev/gen-lang-client-0318381471/cloud-run-source-deploy/lionovart-web:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--allow-unauthenticated'
    - '--timeout'
    - '1800'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'us-central1-docker.pkg.dev/gen-lang-client-0318381471/cloud-run-source-deploy/lionovart-web:$COMMIT_SHA'
