const WebSocket = require("ws");

const STRATEGIST_TOOLS = [
  {
    functionDeclarations: [
      {
        name: "update_screen_info",
        description: "Updates the visual lead form on the user's screen in real-time.",
        parameters: {
          type: "OBJECT",
          properties: {
            name: { type: "STRING", description: "Lead's name" },
            phone: { type: "STRING", description: "Lead's phone number" },
            email: { type: "STRING", description: "Lead's email address" },
          },
        },
      },
      {
        name: "fetch_user_memory",
        description: "Fetches past conversation summaries from the CRM.",
        parameters: {
          type: "OBJECT",
          properties: {
            contact: { type: "STRING", description: "Email address or phone number" },
          },
          required: ["contact"],
        },
      },
      {
        name: "save_lead_data",
        description: "Save the lead's contact information and project context to the CRM.",
        parameters: {
          type: "OBJECT",
          properties: {
            name: { type: "STRING", description: "Lead's full name or first name" },
            phone: { type: "STRING", description: "Lead's phone number" },
            email: { type: "STRING", description: "Lead's email address" },
            project_summary: {
              type: "STRING",
              description: "2-3 sentence summary of their project needs and pain points",
            },
            business_type: { type: "STRING", description: "What kind of business they run" },
          },
          required: ["name", "project_summary"],
        },
      },
      {
        name: "generate_whatsapp_link",
        description: "Generate a WhatsApp deep link pre-filled with context from the conversation.",
        parameters: {
          type: "OBJECT",
          properties: {
            name: { type: "STRING", description: "Lead's name" },
            project_summary: { type: "STRING", description: "Brief context to include in the message" },
          },
          required: ["name", "project_summary"],
        },
      },
      {
        name: "fetch_booking_link",
        description: "Get the Google Calendar appointment booking link for scheduling a call with Leon.",
        parameters: {
          type: "OBJECT",
          properties: {
            timezone: { type: "STRING", description: "The user's timezone if known, otherwise just 'unknown'" }
          },
        },
      },
      {
        name: "show_handoff_cards",
        description: "Displays the final WhatsApp and Google Calendar booking buttons on the user's screen.",
        parameters: {
          type: "OBJECT",
          properties: {
            whatsapp_url: { type: "STRING", description: "The URL generated by generate_whatsapp_link" },
            booking_url: { type: "STRING", description: "The URL fetched by fetch_booking_link" },
            summary_message: { type: "STRING", description: "A short sign-off message confirming the next steps" },
          },
          required: ["whatsapp_url", "booking_url", "summary_message"],
        },
      },
    ]
  }
];

const ws = new WebSocket("ws://localhost:3001/api/strategist/live");

ws.on("open", () => {
  const payload = {
    type: "setup",
    config: {
      responseModalities: ["AUDIO"],
      systemInstruction: {
        parts: [{ text: `You are the LIONOVART AI Brand Strategist — a sharp, warm, and creatively intelligent assistant for LIONOVART, a premium creative agency led by Leonardo (Leon) that specializes in brand identity, web design, and digital strategy.

## YOUR PERSONA
- Creative director energy: confident, curious, and genuinely interested in the person you're talking to
- Warm but not sycophantic — never say "Great question!" or "Absolutely!"
- Speak like a thoughtful creative professional, not a sales bot
- Use concise language — short paragraphs, never walls of text
- Match the user's tone and energy level` }]
      },
      speechConfig: {
        voiceConfig: {
          prebuiltVoiceConfig: {
            voiceName: "Aoede"
          }
        }
      },
      contextWindowCompression: {
        triggerTokens: "104857",
        slidingWindow: { targetTokens: "52428" },
      },
      tools: STRATEGIST_TOOLS
    }
  };
  ws.send(JSON.stringify(payload));
});

ws.on("message", (data) => {
  console.log("Received:", JSON.parse(data.toString()));
  if (JSON.parse(data.toString()).type === "setup_complete") {
     console.log("Setup complete, sending audio and text...");
     const dummyAudio = Buffer.alloc(16000 * 2).toString("base64"); // 1 second of silence
     
     ws.send(JSON.stringify({
       clientContent: {
         turns: [{ role: "user", parts: [{ text: "Hello" }] }],
         turnComplete: true
       }
     }));

     ws.send(JSON.stringify({
       realtimeInput: {
         mediaChunks: [{ mimeType: "audio/pcm;rate=16000", data: dummyAudio }]
       }
     }));
  }
  if (JSON.parse(data.toString()).type === "error") {
     console.error("ERROR RECEIVED!", JSON.parse(data.toString()));
     process.exit(1);
  }
});
